(ns powergrid.util.log
  (:require [taoensso.timbre :as timbre]))

(def ^:macro trace #'timbre/trace)
(def ^:macro trace #'timbre/tracef)
(def ^:macro debug #'timbre/debug)
(def ^:macro debugf #'timbre/debugf)
(def ^:macro info #'timbre/info)
(def ^:macro infof #'timbre/infof)
(def ^:macro warn #'timbre/warn)
(def ^:macro warnf #'timbre/warnf)
(def ^:macro error #'timbre/error)
(def ^:macro errorf #'timbre/errorf)
(def ^:macro fatal #'timbre/fatal)
(def ^:macro fatalf #'timbre/fatalf)
(def ^:macro report #'timbre/report)
(def ^:macro spy #'timbre/spy)
